# Generated by Django 2.0.3 on 2018-03-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsPost', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Post_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
