# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Messages_Subject', models.CharField(max_length=900)),
                ('Messages_Message', models.CharField(max_length=280)),
                ('Messages_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
