# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Area', models.CharField(max_length=100)),
                ('Location_Budget', models.IntegerField()),
                ('Location_City', models.CharField(max_length=100)),
                ('Location_Description', models.CharField(max_length=100)),
                ('Location_District', models.CharField(max_length=100)),
                ('Location_Locality', models.CharField(max_length=100)),
                ('Location_Name', models.CharField(max_length=100)),
                ('Location_Postal_Address', models.CharField(max_length=100)),
                ('Location_Financial', models.CharField(max_length=100)),
                ('Location_Id', models.IntegerField()),
                ('Location_Latitude', models.IntegerField()),
                ('Location_Longitude', models.IntegerField()),
                ('Location_Subcategory', models.CharField(max_length=100)),
                ('Location_Modifications_Allowed', models.CharField(max_length=100)),
                ('Location_Ownership_Status', models.CharField(max_length=100)),
                ('Location_Pincode', models.IntegerField()),
                ('Location_Restrictions', models.CharField(max_length=100)),
                ('Location_State', models.CharField(max_length=100)),
                ('Location_Street_Address', models.CharField(max_length=100)),
                ('Location_Surrounding', models.CharField(max_length=100)),
                ('Location_Modified_Date', models.DateField(auto_now_add=True)),
                ('Location_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
