# Generated by Django 2.0.3 on 2018-04-03 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileProjects_Comment', models.CharField(max_length=150)),
                ('ProfileProjects_Comment_Created_On', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileProjects_Category', models.CharField(max_length=200)),
                ('ProfileProjects_Director', models.CharField(max_length=200)),
                ('ProfileProjects_Production_House', models.CharField(max_length=200)),
                ('ProfileProjects_Title', models.CharField(max_length=200)),
                ('ProfileProjects_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('ProfileProjects_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_ProfileProjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProjects_Comment', to='ProfileProjects.ProfileProjects'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ProfileProjects_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProjects_Commentss', to=settings.AUTH_USER_MODEL),
        ),
    ]
