# Generated by Django 2.0.3 on 2018-03-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmLocationScheduleForPermit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment_FilmLocationScheduleForPermit',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='FilmLocationScheduleForPermit_Comment_Author',
        ),
        migrations.RemoveField(
            model_name='filmlocationscheduleforpermit',
            name='FilmLocationScheduleForPermit_Creator',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FilmLocationScheduleForPermit',
        ),
    ]
