# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pets_Age', models.IntegerField(default=0)),
                ('Pets_Animal_Type', models.CharField(max_length=200)),
                ('Pets_Breed', models.CharField(max_length=200)),
                ('Pets_Daily_Charges', models.IntegerField(default=0)),
                ('Pets_Description', models.CharField(max_length=500)),
                ('Pets_Ownership_Status', models.BooleanField(default=False)),
                ('Pets_Weekly_Charges', models.IntegerField(default=0)),
                ('Pets_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
