# Generated by Django 2.0.3 on 2018-04-03 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoiceOverArtist_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceOverArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoiceOverArtist_Charges_Available', models.BooleanField()),
                ('VoiceOverArtist_Daily_charges', models.IntegerField(default=0)),
                ('VoiceOverArtist_Description', models.CharField(max_length=200)),
                ('VoiceOverArtist_Language', models.CharField(max_length=200)),
                ('VoiceOverArtist_Voice_Scale', models.CharField(max_length=200)),
                ('VoiceOverArtist_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('VoiceOverArtist_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VoiceOverArtist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_VoiceOverArtist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VoiceOverArtist', to='VoiceOverArtist.VoiceOverArtist'),
        ),
        migrations.AddField(
            model_name='comment',
            name='VoiceOverArtist_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VoiceOverArtist_Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
