# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity_Adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amenity_Adresses_Car_Parking', models.CharField(blank=True, max_length=100, null=True)),
                ('Amenity_Adresses_Catering_Base', models.CharField(blank=True, max_length=100, null=True)),
                ('Amenity_Adresses_Genset_Parking', models.CharField(blank=True, max_length=100, null=True)),
                ('Amenity_Adresses_Location_Id', models.CharField(max_length=100, unique=True)),
                ('Amenity_Adresses_Truck_Parking', models.CharField(blank=True, max_length=100, null=True)),
                ('Amenity_Adresses_Vanity_Parking', models.CharField(blank=True, max_length=100, null=True)),
                ('Amenity_Adresses_Modified_Date', models.DateTimeField(auto_now_add=True)),
                ('Amenity_Adresses_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amenity_Adresses_Comment', models.CharField(max_length=150)),
            ],
        ),
    ]
