# Generated by Django 2.0.3 on 2018-03-31 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dancers', '0003_auto_20180331_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dancer',
            old_name='Costume_Created_Date',
            new_name='Dancer_Created_Date',
        ),
        migrations.RenameField(
            model_name='dancer',
            old_name='Costume_Modified_Date',
            new_name='Dancer_Modified_Date',
        ),
    ]
