# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_query_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PermitQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermitQuery_API_Address', models.CharField(max_length=200)),
                ('PermitQuery_City_State_Country', models.CharField(max_length=200)),
                ('PermitQuery_Latitude', models.IntegerField(default=0)),
                ('PermitQuery_Location', models.CharField(max_length=200)),
                ('PermitQuery_Longitude', models.IntegerField(default=0)),
                ('PermitQuery_Map_Address', models.CharField(max_length=100)),
                ('Permit_Query_Number', models.IntegerField(default=0)),
                ('PermitQuery_Query_Mode', models.CharField(max_length=200)),
                ('PermitQuery_Street_Address', models.CharField(max_length=200)),
                ('PermitQuery_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
