# Generated by Django 2.0.3 on 2018-03-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Districts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='District_Message',
        ),
        migrations.AlterField(
            model_name='district',
            name='District_Created_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='District_Modified_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
