# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Districts', '0002_auto_20180331_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DistrictComments', to='Districts.District'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='District_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Districtcommentss', to=settings.AUTH_USER_MODEL),
        ),
    ]
