# Generated by Django 2.0.3 on 2018-03-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCatagory', '0004_auto_20180331_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecatagory',
            name='ServiceCatagory_Message',
        ),
    ]
