# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_pitch_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationPitch_Location_Required', models.CharField(max_length=100)),
                ('LocationPitch_Submitted', models.BooleanField(default=False)),
                ('LocationPitch_Modified_Date', models.DateField(auto_now_add=True)),
                ('LocationPitch_Message', models.CharField(max_length=280)),
                ('LocationPitch_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
