# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Models_Body_Type', models.CharField(max_length=200)),
                ('Models_Description', models.CharField(max_length=200)),
                ('Models_Ethnicity', models.CharField(max_length=200)),
                ('Models_Eye_Colour', models.CharField(max_length=200)),
                ('Models_Hair_Colour', models.CharField(max_length=200)),
                ('Models_Height', models.CharField(max_length=100)),
                ('Models_Scene_Comfort', models.CharField(max_length=200)),
                ('Models_Skin_Color', models.CharField(max_length=200)),
                ('Models_Smoker', models.CharField(max_length=100)),
                ('Models_Special_Skills', models.CharField(max_length=200)),
                ('Models_Weight', models.CharField(max_length=100)),
                ('Models_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
