# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quick_Requirements_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Quick_Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quick_Requirements_Crew_Size', models.IntegerField()),
                ('Quick_Requirements_New_Requirement', models.BooleanField()),
                ('Quick_Requirements_Requirement_Description', models.CharField(max_length=200)),
                ('Quick_Requirements_Shoot_Category', models.CharField(max_length=200)),
                ('Quick_Requirements_Shooting_Region', models.CharField(max_length=200)),
                ('Quick_Requirements_Tentative_Dates', models.DateField(null=True)),
                ('Quick_Requirements_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Quick_Requirements_Modified_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
