# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_Rating', models.IntegerField()),
                ('Review_Text', models.CharField(max_length=200)),
                ('Review_Create_Date', models.DateTimeField(auto_now_add=True)),
                ('Review_Modified_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
