# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_works_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlatformWorks_Client_Name', models.CharField(max_length=200)),
                ('PlatformWorks_Project_Name', models.CharField(max_length=200)),
                ('PlatformWorks_Project_Details', models.CharField(max_length=200)),
                ('PlatformWorks_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
