# Generated by Django 2.0.3 on 2018-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmRecceRoute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmrecceroute',
            name='FilmRecceRoute_Message',
        ),
        migrations.AlterField(
            model_name='filmrecceroute',
            name='FilmRecceRoute_Created_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='filmrecceroute',
            name='FilmRecceRoute_Modified_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
