# Generated by Django 2.0.3 on 2018-03-30 09:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costume_Comment', models.CharField(max_length=150)),
                ('Costume_Comment_Created_On', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costume_Color', models.CharField(max_length=100)),
                ('Costume_Category', models.CharField(max_length=100)),
                ('Costume_Style', models.CharField(max_length=100)),
                ('Costume_Description', models.CharField(max_length=100)),
                ('Costume_Type', models.CharField(max_length=100)),
                ('Costume_Modification_Allowed', models.BooleanField()),
                ('Costume_Trend_Year', models.DateField(default=datetime.datetime(2018, 3, 30, 9, 32, 35, 772471, tzinfo=utc))),
                ('Costume_Weekly_Rent', models.IntegerField()),
                ('Costume_Modified_Date', models.DateField(default=datetime.datetime(2018, 3, 30, 9, 32, 35, 772471, tzinfo=utc))),
                ('Costume_Created_Date', models.DateField(default=datetime.datetime(2018, 3, 30, 9, 32, 35, 772471, tzinfo=utc))),
                ('Costume_Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Costumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Costume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='Costumes.Costume'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Costume_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
