# Generated by Django 2.0.3 on 2018-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume',
            name='Costume_Created_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='costume',
            name='Costume_Modified_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='costume',
            name='Costume_Trend_Year',
            field=models.DateField(auto_now_add=True),
        ),
    ]
