# Generated by Django 2.0.3 on 2018-03-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costumes', '0002_auto_20180330_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume',
            name='Costume_Trend_Year',
            field=models.DateField(),
        ),
    ]
