# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_subcategory_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationSubCategory_Location_Category', models.CharField(max_length=100)),
                ('Location_Subcategory', models.CharField(max_length=100)),
                ('LocationSubCategory_Subcategory_No', models.CharField(max_length=100)),
                ('LocationSubCategory_Modified_Date', models.DateField(auto_now_add=True)),
                ('LocationSubCategory_Message', models.CharField(max_length=280)),
                ('LocationSubCategory_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
