# Generated by Django 2.0.3 on 2018-04-02 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceSubcatagory', '0003_auto_20180402_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ServiceSubcatagory_Comment_Created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
