# Generated by Django 2.0.3 on 2018-03-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EducationInfos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment_Educationinfo',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Educationinfo_Comment_Author',
        ),
        migrations.RemoveField(
            model_name='educationinfo',
            name='Educationinfo_Creator',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Educationinfo',
        ),
    ]
