# Generated by Django 2.0.3 on 2018-03-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationInfos', '0003_auto_20180324_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationinfo',
            name='EducationInfo_Message',
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='EducationInfo_Created_Time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='EducationInfo_Modified_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
