# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Help_Category_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Help_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Help_Category_Name', models.CharField(max_length=100)),
                ('Help_Category_Header_Id', models.IntegerField()),
                ('Help_Category_Modified_Date', models.DateField(auto_now_add=True)),
                ('Help_Category_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
