# Generated by Django 2.0.3 on 2018-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Singer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='Singer_Daily_Charges',
            field=models.IntegerField(),
        ),
    ]
