# Generated by Django 2.0.3 on 2018-04-02 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Singer', '0002_auto_20180328_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='Singer_Singer_ID',
        ),
        migrations.AddField(
            model_name='comment',
            name='Singer_Comment_Created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
