# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PoliceStation_Area_Police_Station', models.CharField(max_length=200)),
                ('PoliceStation_DCP', models.CharField(max_length=200)),
                ('PoliceStation_Station_Name', models.CharField(max_length=200)),
                ('PoliceStation_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
