# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Location_Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_category',
            name='Location_Category_Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_categorys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Location_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_Category.Location_Category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Location_Category_Comment_Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentlocation_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
