# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_City', models.CharField(max_length=100)),
                ('Search_Key_Word', models.CharField(max_length=200)),
                ('Search_Range', models.IntegerField()),
                ('Search_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Search_Modified_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
