# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Amenitie_Location_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location_Amenitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Amenitie_Carparking', models.BooleanField()),
                ('Location_Amenitie_Carparking_Latitide', models.IntegerField()),
                ('Location_Amenitie_Carparking_Longitude', models.IntegerField()),
                ('Location_Amenitie_Catering_Base', models.BooleanField()),
                ('Location_Amenitie_Catering_Base_Latitude', models.IntegerField()),
                ('Location_Amenitie_Catering_Base_Longitude', models.IntegerField()),
                ('Location_Amenitie_Controlling_Status', models.CharField(max_length=100)),
                ('Location_Amenitie_Genset_Parking', models.BooleanField()),
                ('Location_Amenitie_Genset_Parking_Latitude', models.IntegerField()),
                ('Location_Amenitie_Genset_Parking_Longitude', models.IntegerField()),
                ('Location_Amenitie_Location_Id', models.IntegerField()),
                ('Location_Amenitie_Truck_Parking_Latitude', models.IntegerField()),
                ('Location_Amenitie_Truck_Parking_Longitude', models.IntegerField()),
                ('Location_Amenitie_Vanity_Parking', models.BooleanField()),
                ('Location_Amenitie_Vanity_Parking_Latitude', models.IntegerField()),
                ('Location_Amenitie_Vanity_Parking_Longitude', models.IntegerField()),
                ('Location_Amenitie_Washroom', models.BooleanField()),
                ('Location_Amenitie_Modified_Date', models.DateField(auto_now_add=True)),
                ('Location_Amenitie_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
