# Generated by Django 2.0.3 on 2018-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Authority_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LocationAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Authority_Detail', models.CharField(max_length=100)),
                ('Location_Authority_Email', models.EmailField(max_length=254)),
                ('Location_Authority_Google_Address', models.EmailField(default=0, max_length=254)),
                ('Location_Authority_Latitude', models.IntegerField()),
                ('Location_Authority_Longitude', models.IntegerField()),
                ('Location_Authority_Name', models.CharField(max_length=100)),
                ('Location_Authority_Postal_Address', models.CharField(max_length=100)),
                ('Location_Authority_Contact_Number', models.IntegerField()),
                ('Location_Authority_Contact_Name', models.CharField(max_length=100)),
                ('Location_Authority_Locality_City_State', models.CharField(max_length=100)),
                ('Location_Authority_Location_ID', models.IntegerField()),
                ('Location_Authority_Office_Charges', models.IntegerField()),
                ('Location_Authority_Street_Address', models.CharField(max_length=100)),
                ('Location_Authority_Modified_Date', models.DateField(auto_now_add=True)),
                ('Location_Authority_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
