# Generated by Django 2.0.3 on 2018-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmProjectForPermit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmprojectforpermit',
            old_name='FilmProjectForPermit_CrewSize',
            new_name='FilmProjectForPermit_Crew_Size',
        ),
        migrations.RemoveField(
            model_name='filmprojectforpermit',
            name='FilmProjectForPermit_Message',
        ),
        migrations.AlterField(
            model_name='filmprojectforpermit',
            name='FilmProjectForPermit_Created_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='filmprojectforpermit',
            name='FilmProjectForPermit_Modified_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
